version: '2'

services:
  zookeeper:
    image: daocloud.io/jsongo/zookeeper:latest
    container_name: zookeeper 
    restart: always
    environment:
        VERSION: 1.0.3
    #network_mode: host
    ports:
        - 2181:2181
    volumes:
        - /data/zookeeper:/data
        - ./conf:/opt/zookeeper/conf
